### ISSUE TITLE
most recent updates to qtoolkit! 

### ISSUE THREAD

**Issue by lwasser** [earthlab/qtoolkit#1]
- [x] encoding warning - i got this encoding error. i would always assume UTF-8 however do you  know what this is coming from the API?

```
No encoding supplied: defaulting to UTF-8.
```

- [x] Duplicate question error works, however it errors so no data are returned. could it return data or atleast try to?
hey @1papaya  great effort working on this!!
Here is some feedback so far...

```
Error in check_duplicate_question(designs_vector[[i]]) : 
  Error: certificate-science-survey has duplicate question Q24
```
Can the error be a warning? Currently what happens is it fails to load because of the duplicate. a warning would be better with it loading. 

Because it doesn't load, i can't work on the rest of the file... please fix this and i'll keep reviewing! :) 

- [x] at the top of the document, please note that i have some cleanup on Q3. I use this question to create various plots an filter. note that i also use Q18 to filter one response that didn't want to be included. This is why I initially combined both dataframes together. Currently get responses works very well! BUT all of the unique information is lost and i am not able to filter the data as i need to. 

1 solution: Could get_responses return more than one question / column ? I would probably then grab Q3, 18 and 4. Then i could filter as i wished. Sometimes i may need to grab a list of emails or other information to filter. 

- [x] Does `get_responses` allow me to return blanks if i wish? is there an argument so i can account for empty responses?

```
industry_and_science_responses  <- industry_and_science_responses %>%
####   mutate(Q3 = str_replace_all(Q3,
####                               c("Public Sector - Government / Agency" = "Academic",
####                                 "Public Sector \\- Non Govermental Organization \\(NGO\\)" = "Academic",
####                                 "Public Sector \\- Other" = "Academic",
####                                 "Private Sector \\- Industry" = "Industry",
####                                 "Academic / University" = "Academic"))) %>% # remove individual who asked to be removed in the survey data
####   filter(!(str_detect(Q18, "So, I think this is not a survey for me. Please delete me")))
```
This is a great way to work through the use case and optimize the function @1papaya  .

**Comment by 1papaya** [comment]
@ q1: Encoding error is due to Qualtrics responding without a "Content-type:" encoding specified in their response header. I'm working on a fix within the qsurvey package but rest assured it doesn't break anything.

@ q2: Just made the default to only issue a warning on duplicate question. Though I'd say, if anyone ends up working on that question that has a duplicate they will run into some really funky stuff, and that's why I had it error is that really one should never have a duplicate question number ever, so just letting the user know to go into the Qualtrics website and change that. Perhaps that on survey load would be a warning but if the user tries to get_responses/choices/etc on that question it will throw a stop error. Objections?

@ q3: Right now get_responses can return either one question or all of them:
> ```get_responses(survey)```: gets responses to all questions
> ```get_responses(survey, "Q1")```: gets responses to Q1

Also, if you want to grab all the metadata responses too you can run:
> ```get_responses(survey, "Q1", metadata = TRUE)```: includes Q1 responses and all non-question metadata of respondents

If you're looking for a straight dataframe that isn't melted into a key => value pair, so you can filter the rows like you were suggesting, you can do:
> ```get_responses(survey, "Q1", melt = FALSE, metadata = TRUE)```: get back a responses dataframe with metadata

But as I think you can realize, once the data is melted there's no telling which key value pairs belong to a single respondent, so you'll have to filter out while it's still unmelted.

@ q4: You can have get_responses return blanks with rm.blank, and return "Other" with rm.other:
> ```get_responses(survey, "Q1", rm.blank = FALSE, rm.other = FALSE)```: removes no entries

Do let me know your thoughts!!!

**Comment by lwasser** [comment]
awesome. Thanks @1papaya could we provide `get_responses` with a vector of question numbers and have it return more than one question but not the entire survey? i'm going to think a bit about the error (q2). i totally see your reasoning there.

**Comment by 1papaya** [comment]
Issues no longer relevant after rewrite of API
