### ISSUE TITLE
vignettes error - get_survey()

### ISSUE THREAD

**Issue by lwasser** [earthlab/qtoolkit#2]
@1papaya currently i'm getting an error with get survey(). following the vignette i can't seem to get a list of surveys using get_survey(). please have a look. 

```
> connect_qualtrics("cuboulder")
> s_list <- get_survey()
Error in get_survey() : No surveys matched with name ''
> s_list <- get_survey(name = "week")
Error in get_survey(name = "week") : No surveys matched with name 'week'
```

**Comment by 1papaya** [comment]
Updated man pages & vignettes according to changes made in c803940.

get_survey() is now get_surveys() and defaults to matching partial names of available surveys. For instance, what you wrote about will now work, provided you call get_surveys().
```
> s_list <- get_surveys()
> s_list <- get_surveys("week")
```

`load_survey()` provides a shortcut to search for and load the name of a particular survey, and can also be passed a DF returned by get_surveys() and filtered by the user. It defaults to only load exact matches of surveys, but can also be used to wildcard match and return list of surveys.
```
> survey1 <- load_survey("week-1-survey")
> survey1 <- load_survey("SV_surveyidhere")

## using DF of surveys returned by get_surveys()
> survey1 <- load_survey(s_list)

## load list of surveys by wildcard
> surveys <- load_survey("week", match.exact = FALSE)
```

The rationale behind these changes:
- get_surveys() is plural because the default is to match partial name (more than one survey)
- load_survey() is singular because default is to match exact name
- no longer have to specify name="" or id="" because IDs always start with SV_ so it's easy to validate. User can pass either the name or ID as a string
- defaulting to exact name in load_survey() encourages good practice in the user to hardcode names of surveys being used. If user gets used to matching via wildcard there could be more surveys that match that which are added later on, which is not good for reproducibility.
- If user wants to filter the surveys further they can call get_surveys() and manually filter the DF then pass that to load_survey()
