### ISSUE TITLE
unexpected behaviour with get_questions() & code feedback

### ISSUE THREAD

**Issue by lwasser** [earthlab/qtoolkit#6]
Currently, when i run `get_Questions()` it's asking me to make a selection. 

`questions <- get_questions(ea_midterm_design)`

This is odd as yesterday this was working. However i did update qtoolkit so perhaps the version that i'm using now has a few bugs or dev items going on.

Note that this may be because we need to ensure tidyr is a dependency for the package. 
```
Selection: 0
Error in gather(., key = "question", value = "full_text_question") : 
  could not find function "gather"
```
also 
```
Selection: 0
Error in UseMethod("gather_") : 
  no applicable method for 'gather_' applied to an object of class "character"
```

Digging more into this function, it has some issues

- [ ]  The function assumes a quesiton number that begins with a Q and a ID too... I know that you can edit the question numbers and i think the ID could change too. This approach could thus fail. I think the user should be required to either enter a question number as an optional argument. The default function return should be a df of all questions.

- [ ] Do we need to use both the QID and the Q number? what is the purpose of both? it seems to add additional complexity to the code. Let's chat?
```
get_questions <- function(survey,
                          question_num = "Q.*",
                          question_id = "QID.*")
```

- [ ] Next, we filter. This approach limits us to only return questions for one id. But also it adds 2 additional lines of code to the function. If we used an `contains` approach, i think we could simplify the code and make it more robust. I think we could use stringr potentially and avoid regular expressions that are likely to break given different naming conventions.  

- [x] also i think you can use `paste0()` below to avoid the sep argument. And make sure we are following spacing conventions ( `sep=""` vs `sep = ""`)
```
## Filter questions by names passed
  num_filter <- paste("^", question_num, "(\\_|$)", sep="")
  id_filter <- paste("^", question_id, "(\\_|$)", sep="")
```
Here, we could use pipes and mutate

```
## Rename column question_text to question_title
  ## Add column question_text as stripped HTML from question_title
  q_resp$question_raw <- q_resp$question_text
  q_resp$question_text <- strip_html(q_resp$question_raw)
```

like this:

```
q_resp  %>%
  mutate(question_raw = question_text, 
         question_text = strip_html(q_resp$question_raw))
```

The thing that is odd about this code is the it seems to clean the original data and replace what the API returns with that and then create a new column. Why not keep `question_text` as the original text and create a new cleaned column called `question_clean`. This column name tells me that it was modified which i think is good.

So your cleaning step would look like:

```
q_resp  %>%
  mutate(question_text_clean = strip_html(q_resp$question_raw))
```

NOTE -- if question_text is used elsewhere and there's a reason for this step, please let me know. 
Also -- another alternative which may be even better is to have a `clean.html = FALSE` argument. so then you return just one column: question_text that is either cleaned or not cleaned. that is probably the best functionality. As currently the data.frame returned is larger than it needs to be. i can't think of a use case where i'd want both the cleaned and uncleaned in a data.frame UNLESS i was testing things. 

- [ ] Finally - i'm worried that this code could break if the question number doesn't have Q in it. it's really a hard coded regex expression. could the question value be a variable?

```
## Add question number column (turns Q9_1 into Q9)
  q_resp$question_num <- sub("^(Q[0-9]+).*", "\\1",
                             q_resp$export_name)

```

Since we're digging into this code here, i'd like to see what @mbjoseph thinks about using pipes and stringr, etc in this package. i like using it as its much cleaner. it just adds dependencies potentially. 
Thoughts Max?

FUNCTION LOCATION:
https://github.com/earthlab/qtoolkit/blob/1f4efd79ece756f73bd007cece03a2e68d72824f/R/main.R#L77

**Comment by 1papaya** [comment]
> Currently, when i run get_Questions() it's asking me to make a selection.
> 
> questions <- get_questions(ea_midterm_design)
> 
> This is odd as yesterday this was working. However i did update qtoolkit so perhaps the version that i'm using now has a few bugs or dev items going on.
> 
> Note that this may be because we need to ensure tidyr is a dependency for the package.
> ```
> Selection: 0
> Error in gather(., key = "question", value = "full_text_question") : 
>   could not find function "gather"
> ```
> also
> ```
> Selection: 0
> Error in UseMethod("gather_") : 
>   no applicable method for 'gather_' applied to an object of class "character"
> ```

- gather() bug fixed in 838c6de.
- get_questions() working fine for me with just qtoolkit as dependency. Perhaps this was related to the gather() bug up top.

> The function assumes a quesiton number that begins with a Q and a ID too... I know that you can edit the question numbers and i think the ID could change too. This approach could thus fail. I think the user should be required to either enter a question number as an optional argument. The default function return should be a df of all questions.

- Agreed questions need not start with Q, though that's the default. a84505b changes all functions that reference question_num to match any question, not just "Q.*". However, question_id is hardcoded by Qualtrics and is unique (or so says the API docs) so we can safely assume it's "QID.*"

> Do we need to use both the QID and the Q number? what is the purpose of both? it seems to add additional complexity to the code. Let's chat?

- For the use case that surveys are duplicated then modified to be a bit different, question_id seems to persist across those, so this would make cross-referencing reponses between surveys easier, as it could be done automatically. The question_num would persist too but is not guaranteed to be consistent as it could be changed by the user down the line.
- Either way, question_id and question_num are two different identifiers so I think the package should have the option to select via either.

> Next, we filter. This approach limits us to only return questions for one id. But also it adds 2 additional lines of code to the function. If we used an contains approach, i think we could simplify the code and make it more robust. I think we could use stringr potentially and avoid regular expressions that are likely to break given different naming conventions.

- The code works for any number of ids, either passed as a list c("Q9", "Q99") or string "Q9"
- Turns out the code could just work with one line (paste can take either a vector or string), so I consolidated it to:
```
question_num <- paste(question_num, collapse = "|")
num_filter <- paste0("^(", question_num, ")(\\_|$)")
```
- The reason a simple "contains" won't work without some other filtering is that:
1. contains("Q9") will match Q9 and Q99
2. contains("Q9$") will match just Q9 but not Q9_1 which are column names for matrix questions
- For this I used the regex `(\\_|$)` is above, and it can be done otherwise but will likely be a bit convoluted. Right now using paste into the regex will work for the grand majority of use cases, except where the user uses some regex classifier like * in their question name. For most (all?) reasonable use cases this will work

> also i think you can use paste0() below to avoid the sep argument. And make sure we are following spacing conventions ( sep="" vs sep = "")

- Sure thing, all paste()'s are now paste0()'s, throughout all code

> Here, we could use pipes and mutate:
> ```
> ## Rename column question_text to question_title
> ## Add column question_text as stripped HTML from question_title
>  q_resp$question_raw <- q_resp$question_text
>  q_resp$question_text <- strip_html(q_resp$question_raw)
> ```
> like this:
> ```
> q_resp  %>%
>  mutate(question_raw = question_text, 
>         question_text = strip_html(q_resp$question_raw))
> ```

- This doesn't work because we've got to do the column assignments sequentially, ie we want question_raw to be question_text BEFORE it is stripped of HTML. If we do the mutate option as suggested question_raw and question_text both end up being both the stripped of HTML.

> The thing that is odd about this code is the it seems to clean the original data and replace what the API returns with that and then create a new column. Why not keep question_text as the original text and create a new cleaned column called question_clean. This column name tells me that it was modified which i think is good.
>
> So your cleaning step would look like:
>
>```
> q_resp  %>%
>  mutate(question_text_clean = strip_html(q_resp$question_raw))
> ```

- I agree that there should be two separate columns, one with untouched data and one with filtered. For sake of syntax, I think `question_text` to return only the text of the question with no formatting, and `question_raw` being the question as is returned from Qualtrics, is the best description.
- In my opinion, `question_text_clean` doesn't describe what the text was cleaned of, is less descriptive and a long column name, whereas `question_text` and `question_raw` describe better what the columns actually contain. I'm open to discussion 'bout it, and we have the same inclination but different ideas of how to address it.

> NOTE -- if question_text is used elsewhere and there's a reason for this step, please let me know.
Also -- another alternative which may be even better is to have a clean.html = FALSE argument. so then you return just one column: question_text that is either cleaned or not cleaned. that is probably the best functionality. As currently the data.frame returned is larger than it needs to be. i can't think of a use case where i'd want both the cleaned and uncleaned in a data.frame UNLESS i was testing things.

- I'm open to this, though I see a use case for having both be available in analysis. One is, a user can embed hidden identifiers in the questions to be able to be easily selected by (ie. HTML comment `<!-- do_not_use -->`)
- If the question asks something about an image that's embedded with an HTML `<img>` tag, perhaps the user will want the HTML echoed in the Rmd file to display that image?
- In general I think users for sure will want to see the question text with the HTML stripped, and would be amenable to having it be a function parameter as opposed to returning both.

>  Finally - i'm worried that this code could break if the question number doesn't have Q in it. it's really a hard coded regex expression. could the question value be a variable?
> ```
> ## Add question number column (turns Q9_1 into Q9)
>  q_resp$question_num <- sub("^(Q[0-9]+).*", "\\1",
>                             q_resp$export_name)
> ```

- Yep this won't work if the question doesn't begin with Q. Having questions not begin with Q is a major pain in the butt, btw, because the regex has to account for questions that could have any potential underscores in the name, plus there are questions that are formed "Q3_1" (MC) and "Q9#1_1" (matrix).
- Nonetheless, here's some fancy regex that makes it work (committed f94ab94)
```
>  ## Add question number column (turns Q9_1 into Q9)
>  q_resp$question_num <- sub("^(.*?)(\\_|#|$).*", "\\1",
>                             q_resp$export_name)
```

> Since we're digging into this code here, i'd like to see what @mbjoseph thinks about using pipes and stringr, etc in this package. i like using it as its much cleaner. it just adds dependencies potentially.
Thoughts Max?

- Open to suggestions on this; as you might assume I've shied away from bringing on any more dependencies than necessary. So far qtoolkit uses: `dplyr qsurvey tidyr magrittr`

**Comment by mbjoseph** [comment]
I'd avoid adding dependencies unless you expect users to use tidy syntax and pipes with the package.

**Comment by lwasser** [comment]
this is great feedback @1papaya  i'm working through some data and left you a note on slack about get_questions and matrix questions.  

I like your approach of question_raw and question_text but let's make it an option to return one of the other? Or i'd say make the default behaviour the question without the html and then an argument that returns the raw data with the html as a new column. that is probably the best. i really can't see a good use case of needing that html. if the image is embedded it probably lives on qualtrics. you'd probably want it local and wouldn't want to use the terrible qualtrics html to render it :)

**Comment by 1papaya** [comment]
Issues either resolved or no longer relevant due to new API pull request
